baseURL = "https://deathworlders.com/"
languageCode = "en-GB"
title = "The Deathworlders"

theme = "kiera"

pygmentsCodeFences = true

disqusShortname = "" #Disqus shortname
googleAnalytics = "" #Google Analytics ID

[author]
    name = "Philip R. Johnson (Hambone)"       #Author name
    github = "HamboneHFY"     #Github username
    gitlab = ""     #Gitlab username
    linkedin = ""   #LinkedIn username
    facebook = "HamboneHFY"   #Facebook username
    twitter = ""    #Twitter username
    instagram = "HamboneHFY"  #Instagram username
    patreon = "HamboneHFY"

[params]
    tagline = ""
    description = "HFY Stories in the JVerse"

[menu]
    [[menu.main]]
        identifier = "books"
        name = "Books"
        url = "/books"
        weight = 1
